### ISSUE TITLE
compile error(s)...

### ISSUE THREAD

**Issue by amityk77** [abainbridge/sound_shovel#1]
hello abainbridge,

after your comments from DF lib repo, I took a fresh clone of  both the repos... and tried to compile this repo again.

Following are the errors I got:
1>main.cpp
1>k:\research.3\ss\sound_shovel\src\main.cpp(44): error C3861: 'InputManagerAdvance': identifier not found
1>

well project is compliable(not runnable) without that call, but I am not sure of the consequence of skipping that call, as it might belong to DF-lib project.

Also, further when I try to execute the project, I get the following runtime error:
![Screenshot 2021-04-19 202948](https://user-images.githubusercontent.com/20246218/115257918-28dc9d80-a14e-11eb-964b-120c463e433a.png)

Am I missing something.?

**Comment by amityk77** [comment]
> hello abainbridge,
> 
> after your comments from DF lib repo, I took a fresh clone of both the repos... and tried to compile this repo again.
> 
> Following are the errors I got:
> 1>main.cpp
> 1>k:\research.3\ss\sound_shovel\src\main.cpp(44): error C3861: 'InputManagerAdvance': identifier not found
> 1>
> 
> well project is compliable(not runnable) without that call, but I am not sure of the consequence of skipping that call, as it might belong to DF-lib project.
> 
> Also, further when I try to execute the project, I get the following runtime error:
> ![Screenshot 2021-04-19 202948](https://user-images.githubusercontent.com/20246218/115257918-28dc9d80-a14e-11eb-964b-120c463e433a.png)
> 
> Am I missing something.?

Sorry, I forgot to mention, I am using VS2017 Community Edition.

**Comment by amityk77** [comment]
Finally... after some local modifications, I was able to execute the project... but somehow it is not responsive, i.e. I cannot select any menu functions, and/or move the window...
.. Is it because of commenting/removing "InputManagerAdvance" in WinMain function.?

**Comment by amityk77** [comment]
This time, I was able to load wav file, internally using "SoundWidget" constructor... the result is something as below:
(it is screen capture of application)

![Screenshot 2021-04-19 225440](https://user-images.githubusercontent.com/20246218/115278242-db1e6000-a162-11eb-8063-f03536ef736e.png)

but still the application is not responding, and I am not able to do any menu operations or move the window.
is this the actual intention of this project, or am I missing something.? because, in YouTube, the Demo is of full fledged working application.

**Comment by abainbridge** [comment]
I failed to commit a vital change in main.cpp. InputManagerAdvance must be replaced with InputPoll. I've just pushed the fix.

**Comment by amityk77** [comment]
> I failed to commit a vital change in main.cpp. InputManagerAdvance must be replaced with InputPoll. I've just pushed the fix.

great... thanks @abainbridge, now its working... :-)  (though again I had to make some local changes, as after new pull, my earlier changes were gone)

Good Job with this program, as well as with DF lib.. 👍
